-- MySQL Script generated by MySQL Workbench
-- Tue Dec 12 00:34:55 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mon_blog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mon_blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mon_blog` DEFAULT CHARACTER SET utf8 ;
USE `mon_blog` ;

-- -----------------------------------------------------
-- Table `mon_blog`.`Articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mon_blog`.`Articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(255) NOT NULL,
  `chapo` VARCHAR(1000) NOT NULL,
  `contenu` LONGTEXT NOT NULL,
  `date` DATETIME NOT NULL,
  `date_modif` DATETIME NOT NULL,
  `auteur` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idProduit_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
